### PR TITLE
fix: ignore Astro types in index.ts

### PR DESCRIPTION
**Pull request by jlarmstrongiv**
The types will still show in the editor, they just won’t crash when type checking the `index.ts` barrel file

Another alternative is using [`@astrojs/ts-plugin`](https://www.npmjs.com/package/@astrojs/ts-plugin), though you can avoid a dependency by using two comments.  Up to you which you prefer

Though pnpm is broken on my system, so I can’t update the `pnpm-lock.yaml` with [`@astrojs/ts-plugin`](https://www.npmjs.com/package/@astrojs/ts-plugin) on my machine

### CODE REVIEW

**Comment by jlarmstrongiv** [comment]
Closes https://github.com/ascorbic/unpic-img/issues/423

**Comment by ascorbic** [comment]
Is this considered best practice? It seems pretty icky having the `ts-ignore`, but I can't find any docs about what the "correct" way to handle this is for a published component. I do see that [this component template](https://github.com/Princesseuh/component-template/blob/main/index.ts) does the same, which is third-party but recommended in the docs.

**Comment by jlarmstrongiv** [comment]
@ascorbic Unfortunately, I’d say `// @ts-ignore` would probably be the safest solution

I’m getting the TypeScript error despite having [@astrojs/ts-plugin](https://www.npmjs.com/package/@astrojs/ts-plugin) in my project.  There’s a chance having that plugin in the `tsconfig.json` in https://github.com/ascorbic/unpic-img/blob/main/packages/astro/tsconfig.json would fix it, though there’s a chance that won’t be picked up either.

If you publish a version with the [@astrojs/ts-plugin](https://www.npmjs.com/package/@astrojs/ts-plugin), I’ll try it and let you know if it works.  Or you can fall back to `// @ts-ignore`, which I use in an open-source project I maintain.  

Up to you

**Comment by jlarmstrongiv** [comment]
@ascorbic Unfortunately, after further experimentation, the `@ts-ignore` is the only method that works.  If it’s any consolation, that’s how I did it in the Astro integration I made

**Review by ascorbic — APPROVED** [review]

**Comment by ascorbic** [comment]
Thanks. Let's get this in

**Pull request merged**
