### PR TITLE
chore: upgrade svelte dependencies

### PR DESCRIPTION
**Pull request by benmccann**
I have no idea why this is failing on the vue components since I didn't touch those

### CODE REVIEW

**Comment by ascorbic** [comment]
@benmccann Do you have any idea why I'm getting `rune_outside_svelte` errors in the integration tests?

**Comment by benmccann** [comment]
> It's because @testing-library/svelte is installed at the workspace root and that is causing it to use the legacy renderer by default since the root does not have svelte installed.

That wasn't why, but is worth fixing anyway. Needed to specify to resolve in browser mode:  https://svelte.dev/docs/svelte/testing#Unit-and-integration-testing-using-Vitest

**Comment by benmccann** [comment]
@ascorbic this is passing the CI now, but I had to revert your change to upgrade Vite in the preact and react examples

**Comment by ascorbic** [comment]
Great. I only did that change because it was causing problems with conflicting versions. If it's passing now then that's all good. Thans for your help!

**Comment by benmccann** [comment]
@bertybot do you want to send a PR now with your changes to convert the components to runes syntax?

@ascorbic would you be okay with a breaking change to require Svelte 5?

**Comment by benmccann** [comment]
Makes sense. Thanks!

@bertybot let me know if you don't want to do it and I can send it, but otherwise I'll let you do it to get credit for it

**Pull request merged**
