### PR TITLE
React: support ref, fix props case. Core: use breakpoints, fix log error on aspectRatio

### PR DESCRIPTION
**Pull request by eladroz**
For #2

### CODE REVIEW

**Comment by ascorbic** [comment]
Thanks! I'm on holiday right now with no laptop, but I will review this properly next week when I'm back in the country.

**Comment by eladroz** [comment]
@ascorbic have fun! 
meanwhile, this is becoming a bit of an omnibus PR ;-)

**Comment by jasikpark** [comment]
may be helpful to break into multiple PRs in that case 🤷

**Comment by ascorbic** [comment]
Yes. Is it possible for you to split this into two: the one for core and the one for react? It'll mean it does the changelog properly too

**Comment by eladroz** [comment]
Sure can.

**Comment by eladroz** [comment]
Opened #20, #21 in lieu of this PR.

**Comment by ascorbic** [comment]
Perfect, thanks!

**Pull request closed without merging**
