### PR TITLE
chore: setup prettier-plugin-svelte

### PR DESCRIPTION
**Pull request by benmccann**
Can't declare variables with `const` in Svelte or they won't be reactive. You need to use `$:`

### CODE REVIEW

**Comment by ascorbic** [comment]
Thanks! You can tell I'm not very experienced with Svelte! Looks great, but could we do without the prettier changes? I'm happy to add the plugin, but the rest of the repo is formatted using the prettier defaults so I'd like to keep the packages the same if possible.

**Comment by ascorbic** [comment]
Ah, it looks like there's an issue in the tests. Could you take a look? They should be fine to run locally

**Comment by benmccann** [comment]
Thanks. I've reduced this to just the prettier changes for now

**Comment by ascorbic** [comment]
Great, thanks. If I get this in now, will you be able to follow up with the component fix?

**Pull request merged**
